import type { Metadata } from "next";

import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Toaster } from "@/components/ui/sonner";
import { DotPattern } from "@/components/magicui/dot-pattern";
import { cn } from "@/lib/utils";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body suppressHydrationWarning>
        <SidebarProvider>
          <AppSidebar />
          <main>
            <SidebarTrigger />
             <DotPattern
                glow={true} // Ensure DotPattern handles the glow prop
                className={cn(
                  "[mask-image:radial-gradient(300px_circle_at_center,white,transparent)]"
                )}
              />
            {children}
            <Toaster position="top-right" />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
